# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: dbname
    ports:
      - "3306:3306"
    networks:
      - api-network

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - api-network


networks:
  api-network:
    driver: bridge